### PR TITLE
Optionally start conversion for all devices on the bus, resolve #3.

### LINKED ISSUE #3: Improve "start_conversion" method
Hi Robert,

in order to further improve the `start_conversion` method, I would like to suggest this change:
```python
ow = self.ow
ow.reset()
if rom is None:
    ow.write_byte(ow.CMD_SKIPROM)
else:
    ow.select_rom(rom)
ow.write_byte(0x44)  # Convert Temp
```

This would enable us to invoke the method just once for all DS18X20 sensors attached to a single 1-Wire bus and afterwards sequentially collect the readings from the scratch memory of individual sensors.

The proposal is coming from the idea the driver within Genuine MicroPython handles it:
https://github.com/micropython/micropython/blob/v1.11/drivers/onewire/ds18x20.py#L18-L21

With kind regards,
Andreas.

### PR DESCRIPTION
**Pull request by amotl**
The idea is coming from the respective driver within Genuine MicroPython:
https://github.com/micropython/micropython/blob/v1.11/drivers/onewire/ds18x20.py#L18-L21

### CODE REVIEW

**Comment by robert-hh** [comment]
I prefer another method for start_conversion, which I have implemented:
- if there is exactly one device on the bus, rom may be None or omitted.
- if rom is a device number, then this device will be activated 
- if rom is the list of roms, then all devices start conversion. The parameter supplied must be
  the list of roms created during the init call. Since Python assigns lists by reference, this handling
  over of lists is memory efficient.

Code Snippet:
```
        if (rom is None) and (len(self.roms) == 1):
            rom = self.roms[0]

        assert rom is not None, "ROM address missing or ambiguous"

        ow = self.ow
        ow.reset()
        if rom is self.roms: 
            ow.write_byte(ow.CMD_SKIPROM)
        else:
            ow.select_rom(rom)
        ow.write_byte(0x44)  # Convert Temp
```

**Comment by amotl** [comment]
Dear Robert,

we feel the procedure regarding "if there is exactly one device on the bus" is very ambiguous and will not be compatible with Genuine MicroPython anyway, so I proposed to get rid of this within #2. However, I recognize you prefer it that way, so feel free to combine this.

Another way could be to provide the same functionality using a different method like `start_conversion_smart` which has less of a code smell.

With kind regards,
Andreas.

**Comment by robert-hh** [comment]
I'm going to drop that Pycom specific version anyhow and make onewire.py/ds18x20.py mostly compatible to the micryopthon.org version.

**Comment by amotl** [comment]
Thanks a bunch! Then let's just close this in favor of #10.

**Pull request closed without merging**
